export const CAMPUS_LOCATIONS: Record<string, string[]> = {
  'Academic Buildings': [
    'Laz Otti Library',
    'BBS',
    'Education & Humanities Faculty',
    'Post Graduate School',
    'CIBN Bankers Hall',
    'The School of Computing',
    'New Horizon 1',
    'New Horizon 2 (ICT center)',
    'BUCODEL',
    'Alalade Senate Building (Registry)',
  ],
  'Male Hostels': [
    'Gideon Troopers',
    'Winslow',
    'Bethel Splendor',
    'Samuel Akande',
    'Neal Wilson',
    'Nelson Mandela',
    'Welch Hall',
    'Gamaliel Hall',
    'Emerald',
    'Topaz',
  ],
  'Female Hostels': [
    'Felicia Adebisi Dada',
    'Queen Esther',
    'Platinum',
    'Ameyo Adadevoh',
    'Justice Deborah',
    'Havilah Gold',
    'Crystal Hall',
    'White Hall',
    'Nyberg Hall',
    'Ogden Hall',
    'Sapphire',
    'Diamond',
  ],
  'Social & Admin Hubs': [
    'Alalade Senate Building',
    'University Main Church',
    'Central Cafeteria',
    'Babcock Super Store',
    'Amphi Theatre',
    'Sports Complex',
    'Babcock University Teaching Hospital (BUTH)',
    'The University Stadium',
    'The School Gate',
    'Babcock Guest House (BGH)',
    'MSQ Gate',
    'Medical Exit Gate',
  ],
  'Other': ['Other'],
};
